version: "3.8"
services:
  otel-collector:
    image: otel/opentelemetry-collector-contrib:latest
    ports:
      - 4317:4317 # OTLP gRPC
      - 4318:4318 # OTLP HTTP
    volumes:
      - ./:/opt/sloghandler
    command: ["--config=/opt/sloghandler/otel-collector-config.yaml"]
